# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170629_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_project',
            field=models.BooleanField(default=False),
        ),
    ]
